<?php
/**
 * WordPress Export Administration API for Theme Demo Exporter
 *
 * Modified version of the WordPress export function specifically for
 * WBCOM Theme Demo Exporter plugin.
 * 
 * @package WBCOM_Theme_Demo_Exporter
 */

/**
 * Version number for the export format.
 *
 * Bump this when something changes that might affect compatibility.
 *
 * @since 2.5.0
 */
define( 'WXR_VERSION', '1.2' );

/**
 * Generates the WXR export file for download.
 *
 * @since 2.1.0
 *
 * @global wpdb    $wpdb WordPress database abstraction object.
 * @global WP_Post $post Global `$post`.
 *
 * @param array $args Export arguments
 */
function export_wp( $args = array() ) {
    global $wpdb, $post;

    $defaults = array( 
        'content' => 'all', 
        'author' => false, 
        'category' => false,
        'start_date' => false, 
        'end_date' => false, 
        'status' => false,
    );
    
    $args = wp_parse_args( $args, $defaults );

    // Filter hook for plugins to modify export arguments
    do_action( 'export_wp', $args );

    // Generate XML header
    echo '<?xml version="1.0" encoding="' . get_bloginfo('charset') . "\" ?>\n";
    ?>
<!-- This is a WordPress eXtended RSS file generated by WBCOM Theme Demo Exporter plugin -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- This file is intended for theme demo content import purposes. -->

<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/<?php echo WXR_VERSION; ?>/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/<?php echo WXR_VERSION; ?>/"
>

<channel>
    <title><?php bloginfo_rss( 'name' ); ?></title>
    <link><?php bloginfo_rss( 'url' ); ?></link>
    <description><?php bloginfo_rss( 'description' ); ?></description>
    <pubDate><?php echo date( 'D, d M Y H:i:s +0000' ); ?></pubDate>
    <language><?php bloginfo_rss( 'language' ); ?></language>
    <wp:wxr_version><?php echo WXR_VERSION; ?></wp:wxr_version>
    <wp:base_site_url><?php echo wxr_site_url(); ?></wp:base_site_url>
    <wp:base_blog_url><?php bloginfo_rss( 'url' ); ?></wp:base_blog_url>

<?php
    // Build the query to select posts
    if ( 'all' != $args['content'] && post_type_exists( $args['content'] ) ) {
        $ptype = get_post_type_object( $args['content'] );
        if ( ! $ptype->can_export ) {
            $args['content'] = 'post';
        }

        $where = $wpdb->prepare( "{$wpdb->posts}.post_type = %s", $args['content'] );
    } else {
        $post_types = get_post_types( array( 'can_export' => true ) );
        $esses = array_fill( 0, count( $post_types ), '%s' );
        $where = $wpdb->prepare( "{$wpdb->posts}.post_type IN (" . implode( ',', $esses ) . ')', $post_types );
    }

    // Add status condition
    if ( $args['status'] && ( 'post' == $args['content'] || 'page' == $args['content'] ) ) {
        $where .= $wpdb->prepare( " AND {$wpdb->posts}.post_status = %s", $args['status'] );
    } else {
        $where .= " AND {$wpdb->posts}.post_status != 'auto-draft'";
    }

    // Add category condition if specified
    $join = '';
    if ( $args['category'] && 'post' == $args['content'] ) {
        if ( $term = term_exists( $args['category'], 'category' ) ) {
            $join = "INNER JOIN {$wpdb->term_relationships} ON ({$wpdb->posts}.ID = {$wpdb->term_relationships}.object_id)";
            $where .= $wpdb->prepare( " AND {$wpdb->term_relationships}.term_taxonomy_id = %d", $term['term_taxonomy_id'] );
        }
    }

    // Add author/date conditions
    if ( 'post' == $args['content'] || 'page' == $args['content'] || 'attachment' == $args['content'] ) {
        if ( $args['author'] ) {
            $where .= $wpdb->prepare( " AND {$wpdb->posts}.post_author = %d", $args['author'] );
        }

        if ( $args['start_date'] ) {
            $where .= $wpdb->prepare( " AND {$wpdb->posts}.post_date >= %s", date( 'Y-m-d', strtotime( $args['start_date'] ) ) );
        }

        if ( $args['end_date'] ) {
            $where .= $wpdb->prepare( " AND {$wpdb->posts}.post_date < %s", date( 'Y-m-d', strtotime( '+1 month', strtotime( $args['end_date'] ) ) ) );
        }
    }

    // Get post IDs matching our criteria
    $post_ids = $wpdb->get_col( "SELECT ID FROM {$wpdb->posts} $join WHERE $where" );

    // Fetch taxonomy information
    $cats = $tags = $terms = array();
    
    if ( isset( $term ) && $term ) {
        $cat = get_term( $term['term_id'], 'category' );
        $cats = array( $cat->term_id => $cat );
    } elseif ( 'all' == $args['content'] ) {
        // Get all categories, tags, and terms
        $categories = (array) get_categories( array( 'get' => 'all' ) );
        $tags = (array) get_tags( array( 'get' => 'all' ) );
        $custom_taxonomies = get_taxonomies( array( '_builtin' => false ) );
        $custom_terms = (array) get_terms( $custom_taxonomies, array( 'get' => 'all' ) );

        // Process categories
        while ( $cat = array_shift( $categories ) ) {
            if ( $cat->parent == 0 || isset( $cats[$cat->parent] ) ) {
                $cats[$cat->term_id] = $cat;
            } else {
                $categories[] = $cat;
            }
        }

        // Process custom terms
        while ( $t = array_shift( $custom_terms ) ) {
            if ( $t->parent == 0 || isset( $terms[$t->parent] ) ) {
                $terms[$t->term_id] = $t;
            } else {
                $custom_terms[] = $t;
            }
        }
    }

    // Filter for skipping postmeta
    add_filter( 'wxr_export_skip_postmeta', 'wxr_filter_postmeta', 10, 2 );

    // Output authors
    wxr_authors_list( $post_ids );

    // Output taxonomy data
    foreach ( $cats as $c ) {
        echo "\t<wp:category>\n";
        echo "\t\t<wp:term_id>" . intval( $c->term_id ) . "</wp:term_id>\n";
        echo "\t\t<wp:category_nicename>" . wxr_cdata( $c->slug ) . "</wp:category_nicename>\n";
        echo "\t\t<wp:category_parent>" . wxr_cdata( $c->parent ? $cats[$c->parent]->slug : '' ) . "</wp:category_parent>\n";
        wxr_cat_name( $c );
        wxr_category_description( $c );
        wxr_term_meta( $c );
        echo "\t</wp:category>\n";
    }

    foreach ( $tags as $t ) {
        echo "\t<wp:tag>\n";
        echo "\t\t<wp:term_id>" . intval( $t->term_id ) . "</wp:term_id>\n";
        echo "\t\t<wp:tag_slug>" . wxr_cdata( $t->slug ) . "</wp:tag_slug>\n";
        wxr_tag_name( $t );
        wxr_tag_description( $t );
        wxr_term_meta( $t );
        echo "\t</wp:tag>\n";
    }

    foreach ( $terms as $t ) {
        echo "\t<wp:term>\n";
        echo "\t\t<wp:term_id>" . wxr_cdata( $t->term_id ) . "</wp:term_id>\n";
        echo "\t\t<wp:term_taxonomy>" . wxr_cdata( $t->taxonomy ) . "</wp:term_taxonomy>\n";
        echo "\t\t<wp:term_slug>" . wxr_cdata( $t->slug ) . "</wp:term_slug>\n";
        echo "\t\t<wp:term_parent>" . wxr_cdata( $t->parent ? $terms[$t->parent]->slug : '' ) . "</wp:term_parent>\n";
        wxr_term_name( $t );
        wxr_term_description( $t );
        wxr_term_meta( $t );
        echo "\t</wp:term>\n";
    }

    // Output nav menu terms if exporting 'all' content
    if ( 'all' == $args['content'] || 'nav_menu_item' == $args['content'] ) {
        wxr_nav_menu_terms();
    }

    // Allow plugins to add custom XML nodes
    do_action( 'rss2_head' );

    // Process posts in batches to prevent memory issues
    if ( $post_ids ) {
        global $wp_query;

        // Fake being in the loop
        $wp_query->in_the_loop = true;

        // Process posts in batches of 20
        while ( $next_posts = array_splice( $post_ids, 0, 20 ) ) {
            $where = 'WHERE ID IN (' . implode( ',', $next_posts ) . ')';
            $posts = $wpdb->get_results( "SELECT * FROM {$wpdb->posts} $where" );

            // Process each post
            foreach ( $posts as $post ) {
                setup_postdata( $post );
                $is_sticky = is_sticky( $post->ID ) ? 1 : 0;
                ?>
    <item>
        <title><?php echo apply_filters( 'the_title_rss', $post->post_title ); ?></title>
        <link><?php the_permalink_rss(); ?></link>
        <pubDate><?php echo mysql2date( 'D, d M Y H:i:s +0000', get_post_time( 'Y-m-d H:i:s', true ), false ); ?></pubDate>
        <dc:creator><?php echo wxr_cdata( get_the_author_meta( 'login' ) ); ?></dc:creator>
        <guid isPermaLink="false"><?php the_guid(); ?></guid>
        <description></description>
        <content:encoded><?php 
            // Replace internal URLs with placeholder
            $content = $post->post_content;
            $content = str_replace(get_site_url(), '{{*home_url}}', $content);
            echo wxr_cdata( apply_filters( 'the_content_export', $content ) ); 
        ?></content:encoded>
        <excerpt:encoded><?php 
            echo wxr_cdata( apply_filters( 'the_excerpt_export', $post->post_excerpt ) ); 
        ?></excerpt:encoded>
        <wp:post_id><?php echo intval( $post->ID ); ?></wp:post_id>
        <wp:post_date><?php echo wxr_cdata( $post->post_date ); ?></wp:post_date>
        <wp:post_date_gmt><?php echo wxr_cdata( $post->post_date_gmt ); ?></wp:post_date_gmt>
        <wp:comment_status><?php echo wxr_cdata( $post->comment_status ); ?></wp:comment_status>
        <wp:ping_status><?php echo wxr_cdata( $post->ping_status ); ?></wp:ping_status>
        <wp:post_name><?php echo wxr_cdata( $post->post_name ); ?></wp:post_name>
        <wp:status><?php echo wxr_cdata( $post->post_status ); ?></wp:status>
        <wp:post_parent><?php echo intval( $post->post_parent ); ?></wp:post_parent>
        <wp:menu_order><?php echo intval( $post->menu_order ); ?></wp:menu_order>
        <wp:post_type><?php echo wxr_cdata( $post->post_type ); ?></wp:post_type>
        <wp:post_password><?php echo wxr_cdata( $post->post_password ); ?></wp:post_password>
        <wp:is_sticky><?php echo intval( $is_sticky ); ?></wp:is_sticky>
<?php 
                // Add attachment URL for media files
                if ( $post->post_type == 'attachment' ) : 
                    $attachment_url = wp_get_attachment_url( $post->ID );
                    // Replace internal URLs with placeholder
                    $attachment_url = str_replace(get_site_url(), '{{*home_url}}', $attachment_url);
?>
        <wp:attachment_url><?php echo wxr_cdata( $attachment_url ); ?></wp:attachment_url>
<?php 
                endif;
                
                // Add taxonomy data 
                wxr_post_taxonomy();
                
                // Add post meta
                $postmeta = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM $wpdb->postmeta WHERE post_id = %d", $post->ID ) );
                foreach ( $postmeta as $meta ) {
                    // Skip meta if filtered
                    if ( apply_filters( 'wxr_export_skip_postmeta', false, $meta->meta_key, $meta ) ) {
                        continue;
                    }
                    
                    // Process and sanitize meta value
                    $meta_value = $meta->meta_value;
                    
                    // Replace site URLs in meta values
                    if (is_serialized($meta_value)) {
                        $unserialized = maybe_unserialize($meta_value);
                        if (is_array($unserialized) || is_object($unserialized)) {
                            // We need to handle serialized data carefully
                            // For demo purposes, we'll only replace URLs in serialized strings
                            $meta_value = str_replace(get_site_url(), '{{*home_url}}', $meta_value);
                        }
                    } else if (is_string($meta_value)) {
                        $meta_value = str_replace(get_site_url(), '{{*home_url}}', $meta_value);
                    }
?>
        <wp:postmeta>
            <wp:meta_key><?php echo wxr_cdata( $meta->meta_key ); ?></wp:meta_key>
            <wp:meta_value><?php echo wxr_cdata( $meta_value ); ?></wp:meta_value>
        </wp:postmeta>
<?php
                }

                // Add comments
                $comments = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM $wpdb->comments WHERE comment_post_ID = %d AND comment_approved <> 'spam'", $post->ID ) );
                if ( $comments ) {
                    foreach ( $comments as $c ) {
?>
        <wp:comment>
            <wp:comment_id><?php echo intval( $c->comment_ID ); ?></wp:comment_id>
            <wp:comment_author><?php echo wxr_cdata( $c->comment_author ); ?></wp:comment_author>
            <wp:comment_author_email><?php echo wxr_cdata( $c->comment_author_email ); ?></wp:comment_author_email>
            <wp:comment_author_url><?php echo esc_url_raw( $c->comment_author_url ); ?></wp:comment_author_url>
            <wp:comment_author_IP><?php echo wxr_cdata( $c->comment_author_IP ); ?></wp:comment_author_IP>
            <wp:comment_date><?php echo wxr_cdata( $c->comment_date ); ?></wp:comment_date>
            <wp:comment_date_gmt><?php echo wxr_cdata( $c->comment_date_gmt ); ?></wp:comment_date_gmt>
            <wp:comment_content><?php echo wxr_cdata( $c->comment_content ) ?></wp:comment_content>
            <wp:comment_approved><?php echo wxr_cdata( $c->comment_approved ); ?></wp:comment_approved>
            <wp:comment_type><?php echo wxr_cdata( $c->comment_type ); ?></wp:comment_type>
            <wp:comment_parent><?php echo intval( $c->comment_parent ); ?></wp:comment_parent>
            <wp:comment_user_id><?php echo intval( $c->user_id ); ?></wp:comment_user_id>
<?php
                        // Add comment meta
                        $c_meta = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM $wpdb->commentmeta WHERE comment_id = %d", $c->comment_ID ) );
                        foreach ( $c_meta as $meta ) {
                            if ( apply_filters( 'wxr_export_skip_commentmeta', false, $meta->meta_key, $meta ) ) {
                                continue;
                            }
?>
            <wp:commentmeta>
                <wp:meta_key><?php echo wxr_cdata( $meta->meta_key ); ?></wp:meta_key>
                <wp:meta_value><?php echo wxr_cdata( $meta->meta_value ); ?></wp:meta_value>
            </wp:commentmeta>
<?php 
                        }
?>
        </wp:comment>
<?php
                    }
                }
?>
    </item>
<?php
            }
        }
    }
?>
</channel>
</rss>
<?php
}

/**
 * Wrap given string in XML CDATA tag.
 *
 * @since 2.1.0
 *
 * @param string $str String to wrap in XML CDATA tag.
 * @return string
 */
function wxr_cdata( $str ) {
    if ( ! seems_utf8( $str ) ) {
        $str = utf8_encode( $str );
    }
    
    $str = '<![CDATA[' . str_replace( ']]>', ']]]]><![CDATA[>', $str ) . ']]>';
    return $str;
}

/**
 * Return the URL of the site
 *
 * @since 2.5.0
 *
 * @return string Site URL.
 */
function wxr_site_url() {
    // Multisite: the base URL.
    if ( is_multisite() ) {
        return network_home_url();
    }
    // WordPress (single site): the blog URL.
    else {
        return get_bloginfo_rss( 'url' );
    }
}

/**
 * Output a cat_name XML tag from a given category object
 *
 * @since 2.1.0
 *
 * @param object $category Category Object
 */
function wxr_cat_name( $category ) {
    if ( empty( $category->name ) ) {
        return;
    }

    echo "\t\t<wp:cat_name>" . wxr_cdata( $category->name ) . "</wp:cat_name>\n";
}

/**
 * Output a category_description XML tag from a given category object
 *
 * @since 2.1.0
 *
 * @param object $category Category Object
 */
function wxr_category_description( $category ) {
    if ( empty( $category->description ) ) {
        return;
    }

    echo "\t\t<wp:category_description>" . wxr_cdata( $category->description ) . "</wp:category_description>\n";
}

/**
 * Output a tag_name XML tag from a given tag object
 *
 * @since 2.3.0
 *
 * @param object $tag Tag Object
 */
function wxr_tag_name( $tag ) {
    if ( empty( $tag->name ) ) {
        return;
    }

    echo "\t\t<wp:tag_name>" . wxr_cdata( $tag->name ) . "</wp:tag_name>\n";
}

/**
 * Output a tag_description XML tag from a given tag object
 *
 * @since 2.3.0
 *
 * @param object $tag Tag Object
 */
function wxr_tag_description( $tag ) {
    if ( empty( $tag->description ) ) {
        return;
    }

    echo "\t\t<wp:tag_description>" . wxr_cdata( $tag->description ) . "</wp:tag_description>\n";
}

/**
 * Output a term_name XML tag from a given term object
 *
 * @since 2.9.0
 *
 * @param object $term Term Object
 */
function wxr_term_name( $term ) {
    if ( empty( $term->name ) ) {
        return;
    }

    echo "\t\t<wp:term_name>" . wxr_cdata( $term->name ) . "</wp:term_name>\n";
}

/**
 * Output a term_description XML tag from a given term object
 *
 * @since 2.9.0
 *
 * @param object $term Term Object
 */
function wxr_term_description( $term ) {
    if ( empty( $term->description ) ) {
        return;
    }

    echo "\t\t<wp:term_description>" . wxr_cdata( $term->description ) . "</wp:term_description>\n";
}

/**
 * Output term meta XML tags for a given term object.
 *
 * @since 4.6.0
 *
 * @param WP_Term $term Term object.
 */
function wxr_term_meta( $term ) {
    global $wpdb;

    $termmeta = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM $wpdb->termmeta WHERE term_id = %d", $term->term_id ) );

    foreach ( $termmeta as $meta ) {
        /**
         * Filters whether to selectively skip term meta used for WXR exports.
         *
         * @since 4.6.0
         *
         * @param bool   $skip     Whether to skip the current piece of term meta. Default false.
         * @param string $meta_key Current meta key.
         * @param object $meta     Current meta object.
         */
        if ( ! apply_filters( 'wxr_export_skip_termmeta', false, $meta->meta_key, $meta ) ) {
            printf( "\t\t<wp:termmeta>\n\t\t\t<wp:meta_key>%s</wp:meta_key>\n\t\t\t<wp:meta_value>%s</wp:meta_value>\n\t\t</wp:termmeta>\n", 
                wxr_cdata( $meta->meta_key ), 
                wxr_cdata( $meta->meta_value )
            );
        }
    }
}

/**
 * Output list of authors with posts
 *
 * @since 3.1.0
 *
 * @global wpdb $wpdb WordPress database abstraction object.
 *
 * @param array $post_ids Array of post IDs to filter the query by. Optional.
 */
function wxr_authors_list( array $post_ids = null ) {
    global $wpdb;

    if ( !empty( $post_ids ) ) {
        $post_ids = array_map( 'absint', $post_ids );
        $and = 'AND ID IN ( ' . implode( ', ', $post_ids ) . ')';
    } else {
        $and = '';
    }

    $authors = array();
    $results = $wpdb->get_results( "SELECT DISTINCT post_author FROM $wpdb->posts WHERE post_status != 'auto-draft' $and" );
    
    foreach ( (array) $results as $result ) {
        $authors[] = get_userdata( $result->post_author );
    }

    $authors = array_filter( $authors );

    foreach ( $authors as $author ) {
        echo "\t<wp:author>";
        echo '<wp:author_id>' . intval( $author->ID ) . '</wp:author_id>';
        echo '<wp:author_login>' . wxr_cdata( $author->user_login ) . '</wp:author_login>';
        echo '<wp:author_email>' . wxr_cdata( $author->user_email ) . '</wp:author_email>';
        echo '<wp:author_display_name>' . wxr_cdata( $author->display_name ) . '</wp:author_display_name>';
        echo '<wp:author_first_name>' . wxr_cdata( $author->first_name ) . '</wp:author_first_name>';
        echo '<wp:author_last_name>' . wxr_cdata( $author->last_name ) . '</wp:author_last_name>';
        echo "</wp:author>\n";
    }
}

/**
 * Output all navigation menu terms
 *
 * @since 3.1.0
 */
function wxr_nav_menu_terms() {
    $nav_menus = wp_get_nav_menus();
    if ( empty( $nav_menus ) || ! is_array( $nav_menus ) ) {
        return;
    }

    foreach ( $nav_menus as $menu ) {
        echo "\t<wp:term>";
        echo '<wp:term_id>' . intval( $menu->term_id ) . '</wp:term_id>';
        echo '<wp:term_taxonomy>nav_menu</wp:term_taxonomy>';
        echo '<wp:term_slug>' . wxr_cdata( $menu->slug ) . '</wp:term_slug>';
        wxr_term_name( $menu );
        echo "</wp:term>\n";
    }
}

/**
 * Output list of taxonomy terms, in XML tag format, associated with a post
 *
 * @since 2.3.0
 */
function wxr_post_taxonomy() {
    $post = get_post();

    $taxonomies = get_object_taxonomies( $post->post_type );
    if ( empty( $taxonomies ) ) {
        return;
    }
    
    $terms = wp_get_object_terms( $post->ID, $taxonomies );

    foreach ( (array) $terms as $term ) {
        echo "\t\t<category domain=\"{$term->taxonomy}\" nicename=\"{$term->slug}\">" . wxr_cdata( $term->name ) . "</category>\n";
    }
}

/**
 * Filters what postmeta to skip during export
 *
 * @param bool   $return_me Whether to skip this meta key
 * @param string $meta_key The meta key being checked
 * @return bool Whether to skip the meta key
 */
function wxr_filter_postmeta( $return_me, $meta_key ) {
    // Skip edit lock meta
    if ( '_edit_lock' == $meta_key ) {
        return true;
    }
    
    // Skip other temporary meta
    $skip_meta_keys = array(
        '_edit_last',      // Last edited by user ID
        '_wp_old_slug',    // Old slugs
        '_wp_trash_meta',  // Trash metadata
    );
    
    if (in_array($meta_key, $skip_meta_keys)) {
        return true;
    }
    
    return $return_me;
}